### PR TITLE
show interfaces parsing was incorrect due to only allowing for up interfaces

### PR DESCRIPTION
**Pull request by wiggimt**
Changed to allow (up|down|administratively down)

Signed-off-by: Michael Wiggins <wiggimt@gmail.com>

### CODE REVIEW

**Comment by LukeDRussell** [comment]
Could we include a parser to show if the interface is up / down / admin down?

**Comment by wiggimt** [comment]
The parser (as written) already correctly parses the following. This pull only fixes the matches for {{context}} to address all interfaces. 

Interface admin-up, proto-up:
    admin-status: enabled
    enabled: true
    oper-status: up
Interface admin-down, proto-down:
    admin-status: disabled
    enabled: false
    oper-status: down
Interface admin-up, proto-down:
    admin-status: enabled
    enabled: true
    oper-status: down

You could add a pattern_match for a **status** variable that would capture "_Interface_ is (**status**), ..."

**Review by gdpak — CHANGES_REQUESTED** [review]
@wiggimt To keep backward compatibility. we can make it configurable with default behaviour being only collecting 'up' interface as facts.
```
--- a/parser_templates/cli/show_interfaces.yaml
+++ b/parser_templates/cli/show_interfaces.yaml
@@ -7,7 +7,7 @@
 
 - name: match sections
   pattern_match:
-    regex: "^\\S+ is up,"
+    regex: "^\\S+ is {{ interface_state_in_facts }},"
     match_all: yes
     match_greedy: yes
   register: context
diff --git a/defaults/main.yml b/defaults/main.yml
index 7fb98f2..6464fc2 100644
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -11,4 +11,5 @@ ios_config_source:
 ios_get_facts_command_map: "{{ role_path }}/vars/get_facts_command_map.yaml"
 ios_get_facts_subset: "{{ subset | default(['default']) }}"
 ios_dependent_role_check: True
+interface_state_in_facts: 'up'
```
and one can set his desired state of interface to be collected in playbook like below
```
    - name: get interfaces                                                                                                                                                  
      include_role:                                                                                                                                                           
        name: ansible-network.cisco_ios                                                                                                                                                 
        tasks_from: get_facts                                                                                                                                                 
      vars:                                                                                                                                                                   
        subset:                                                                                                                                                               
          - interfaces                                                                                                                                                        
        interface_state_in_facts: '(up|down|administratively down)'                                                                                                           
  ```

**Comment by wiggimt** [comment]
The previous code is actually broken. I should probably write this as a test, but here's a quick view, take a look at GigabitEthernet0/0/1. As you can see, vars like **enabled** fail to parse correctly since multiple disabled interfaces are rolled up into a matching group with the live one.

Device state:
```
GigabitEthernet0/0/0 is up, line protocol is up
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d500 (bia e4aa.5df7.d500)
  Description: internal DMZ
  Internet address is 1.1.1.1/27
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is SX
  output flow-control is on, input flow-control is on
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input 00:00:00, output 00:00:39, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     812732 packets input, 74259217 bytes, 0 no buffer
     Received 6787 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 775394 multicast, 0 pause input
     21312 packets output, 8435730 bytes, 0 underruns
     0 output errors, 0 collisions, 2 interface resets
     39083 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0/0/1 is up, line protocol is up
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d501 (bia e4aa.5df7.d501)
  Description: external DMZ
  Internet address is 2.2.2.2/27
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is SX
  output flow-control is on, input flow-control is on
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input 00:00:00, output 00:00:00, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 1000 bits/sec, 1 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     2661846 packets input, 183686421 bytes, 0 no buffer
     Received 1753578 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 833407 multicast, 0 pause input
     65792 packets output, 11180901 bytes, 0 underruns
     0 output errors, 0 collisions, 2 interface resets
     40944 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0/0/2 is administratively down, line protocol is down
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d502 (bia e4aa.5df7.d502)
  Internet address is 3.3.3.3/29
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is unknown media type
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 1 interface resets
     0 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0/0/3 is administratively down, line protocol is down
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d503 (bia e4aa.5df7.d503)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is unknown media type
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 1 interface resets
     0 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0/0/3.2001 is administratively down, line protocol is down
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d503 (bia e4aa.5df7.d503)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation QinQ Virtual LAN, outer ID  2001, inner ID 100
  ARP type: ARPA, ARP Timeout 04:00:00
  Keepalive not supported
  Last clearing of "show interface" counters never
GigabitEthernet0/0/4 is administratively down, line protocol is down
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d504 (bia e4aa.5df7.d504)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is unknown media type
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 1 interface resets
     0 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0/0/5 is administratively down, line protocol is down
  Hardware is 6XGE-BUILT-IN, address is e4aa.5df7.d505 (bia e4aa.5df7.d505)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive not supported
  Full Duplex, 1000Mbps, link type is auto, media type is unknown media type
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 1 interface resets
     0 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
GigabitEthernet0 is up, line protocol is up
  Hardware is RP management port, address is e4aa.5df7.d540 (bia e4aa.5df7.d540)
  Description: mgmt Interface
  Internet address is 4.4.4.4/24
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full Duplex, 1000Mbps, link type is auto, media type is RJ45
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input 00:00:00, output 00:00:00, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 4000 bits/sec, 7 packets/sec
  5 minute output rate 1000 bits/sec, 1 packets/sec
     6604971 packets input, 491265219 bytes, 0 no buffer
     Received 4891144 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     190759 packets output, 22542951 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     18617 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
Loopback0 is up, line protocol is up
  Hardware is Loopback
  MTU 1514 bytes, BW 8000000 Kbit/sec, DLY 5000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation LOOPBACK, loopback not set
  Keepalive set (10 sec)
  Last input never, output never, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/0 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
Tunnel0 is up, line protocol is down
  Hardware is Tunnel
  Description: Pim Register Tunnel (Encap) for RP 5.5.5.5
  MTU 9972 bytes, BW 100 Kbit/sec, DLY 50000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation TUNNEL, loopback not set
  Keepalive not set
  Tunnel linestate evaluation down - no IPv4 tunnel source address
  Tunnel source UNKNOWN, destination 5.5.5.5
  Tunnel protocol/transport PIM/IPv4
  Tunnel TTL 255
  Tunnel transport MTU 1472 bytes
  Tunnel is transmit only
  Tunnel transmit bandwidth 8000 (kbps)
  Tunnel receive bandwidth 8000 (kbps)
  Last input never, output never, output hang never
  Last clearing of "show interface" counters 1w5d
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/0 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
Tunnel1 is up, line protocol is up
  Hardware is Tunnel
  Description: tunnel for gloabl routing for c-hub
  Internet address will be negotiated using IKEv2 Modeconfig
  MTU 9976 bytes, BW 100 Kbit/sec, DLY 50000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation TUNNEL, loopback not set
  Keepalive not set
  Tunnel linestate evaluation up
  Tunnel source 6.6.6.6 (GigabitEthernet0/0/1), destination 7.7.7.7
   Tunnel Subblocks:
      src-track:
         Tunnel1 source tracking subblock associated with GigabitEthernet0/0/1
          Set of tunnels with source GigabitEthernet0/0/1, 2 members (includes iterators), on interface <OK>
  Tunnel protocol/transport GRE/IP
    Key disabled, sequencing disabled
    Checksumming of packets disabled
  Tunnel TTL 255, Fast tunneling enabled
  Path MTU Discovery, ager 10 mins, min MTU 92
  Tunnel transport MTU 1476 bytes
  Tunnel transmit bandwidth 8000 (kbps)
  Tunnel receive bandwidth 8000 (kbps)
  Last input never, output never, output hang never
  Last clearing of "show interface" counters 1w5d
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/0 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
Tunnel2 is administratively down, line protocol is down
  Hardware is Tunnel
  Description: tunnel for gloabl routing for SJC
  Internet address will be negotiated using IKEv2 Modeconfig
  MTU 10000 bytes, BW 100 Kbit/sec, DLY 50000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation TUNNEL, loopback not set
  Keepalive not set
  Tunnel linestate evaluation down - interface not up
  Tunnel source 8.8.8.8 (GigabitEthernet0/0/1), destination 9.9.9.9
   Tunnel Subblocks:
      src-track:
         Tunnel2 source tracking subblock associated with GigabitEthernet0/0/1
          Set of tunnels with source GigabitEthernet0/0/1, 2 members (includes iterators), on interface <OK>
  Tunnel protocol/transport GRE/IP
    Key disabled, sequencing disabled
    Checksumming of packets disabled
  Tunnel TTL 255, Fast tunneling enabled
  Path MTU Discovery, ager 10 mins, min MTU 92
  Tunnel transport MTU 1476 bytes
  Tunnel transmit bandwidth 8000 (kbps)
  Tunnel receive bandwidth 8000 (kbps)
  Last input never, output never, output hang never
  Last clearing of "show interface" counters 1w5d
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/0 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
Virtual-Access1 is down, line protocol is down
  Hardware is Virtual Access interface
  MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation PPP, LCP Closed
  Base VtMgr vaccess
  Vaccess status 0x0, loopback not set
  Keepalive set (10 sec)
  DTR is pulsed for 5 seconds on reset
  Last input never, output never, output hang never
  Last clearing of "show interface" counters 1w5d
  Input queue: 0/4096/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
     0 carrier transitions
Virtual-Template1 is down, line protocol is down
  Hardware is Virtual Template interface
  MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100000 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation PPP, LCP Closed, loopback not set
  Keepalive set (10 sec)
  DTR is pulsed for 5 seconds on reset
  Last input never, output never, output hang never
  Last clearing of "show interface" counters 1w5d
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
     0 carrier transitions
```
Before:
```
      interfaces:
        GigabitEthernet0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '4892791'
            in-multicast-pkts: null
            in-octets: '6607424'
            in-unicast-pkts: '491444414'
            out-errors: '0'
            out-octets: '191233'
            out-unicast-pkts: '22652102'
          description: mgmt Interface
          enabled: true
          mtu: '1500'
          name: GigabitEthernet0
          oper-status: up
          type: RP
        GigabitEthernet0/0/0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '6788'
            in-multicast-pkts: null
            in-octets: '812994'
            in-unicast-pkts: '74282917'
            out-errors: '0'
            out-octets: '21319'
            out-unicast-pkts: '8438572'
          description: internal DMZ
          enabled: true
          mtu: '1500'
          name: GigabitEthernet0/0/0
          oper-status: up
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/1:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '1754115'
            in-multicast-pkts: null
            in-octets: '2662677'
            in-unicast-pkts: '183743970'
            out-errors: '0'
            out-octets: '65853'
            out-unicast-pkts: '11187233'
          description: external DMZ
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/1
          oper-status: up
          type: 6XGE-BUILT-IN,
        Loopback0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: true
          mtu: '1514'
          name: Loopback0
          oper-status: up
          type: Loopback
        Tunnel0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: Pim Register Tunnel (Encap) for RP 139.65.245.226
          enabled: true
          mtu: '9972'
          name: Tunnel0
          oper-status: down
          type: Tunnel
        Tunnel1:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: tunnel for gloabl routing for c-hub
          enabled: false
          mtu: '9976'
          name: Tunnel1
          oper-status: up
          type: Tunnel
```
After:
```
      interfaces:
        GigabitEthernet0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '4892264'
            in-multicast-pkts: null
            in-octets: '6606555'
            in-unicast-pkts: '491380551'
            out-errors: '0'
            out-octets: '190970'
            out-unicast-pkts: '22588390'
          description: mgmt Interface
          enabled: true
          mtu: '1500'
          name: GigabitEthernet0
          oper-status: up
          type: RP
        GigabitEthernet0/0/0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '6787'
            in-multicast-pkts: null
            in-octets: '812904'
            in-unicast-pkts: '74274781'
            out-errors: '0'
            out-octets: '21317'
            out-unicast-pkts: '8437760'
          description: internal DMZ
          enabled: true
          mtu: '1500'
          name: GigabitEthernet0/0/0
          oper-status: up
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/1:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '1753917'
            in-multicast-pkts: null
            in-octets: '2662375'
            in-unicast-pkts: '183723273'
            out-errors: '0'
            out-octets: '65832'
            out-unicast-pkts: '11185156'
          description: external DMZ
          enabled: true
          mtu: '1500'
          name: GigabitEthernet0/0/1
          oper-status: up
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/2:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/2
          oper-status: down
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/3:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/3
          oper-status: down
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/3.2001:
          admin-status: disabled
          counters:
            in-broadcast-pkts: null
            in-multicast-pkts: null
            in-octets: null
            in-unicast-pkts: null
            out-errors: null
            out-octets: null
            out-unicast-pkts: null
          description: null
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/3.2001
          oper-status: down
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/4:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/4
          oper-status: down
          type: 6XGE-BUILT-IN,
        GigabitEthernet0/0/5:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: false
          mtu: '1500'
          name: GigabitEthernet0/0/5
          oper-status: down
          type: 6XGE-BUILT-IN,
        Loopback0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: true
          mtu: '1514'
          name: Loopback0
          oper-status: up
          type: Loopback
        Tunnel0:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: Pim Register Tunnel (Encap) for RP 139.65.245.226
          enabled: true
          mtu: '9972'
          name: Tunnel0
          oper-status: down
          type: Tunnel
        Tunnel1:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: tunnel for gloabl routing for c-hub
          enabled: true
          mtu: '9976'
          name: Tunnel1
          oper-status: up
          type: Tunnel
        Tunnel2:
          admin-status: disabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: tunnel for gloabl routing for SJC
          enabled: false
          mtu: '10000'
          name: Tunnel2
          oper-status: down
          type: Tunnel
        Virtual-Access1:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: true
          mtu: '1500'
          name: Virtual-Access1
          oper-status: down
          type: Virtual
        Virtual-Template1:
          admin-status: enabled
          counters:
            in-broadcast-pkts: '0'
            in-multicast-pkts: null
            in-octets: '0'
            in-unicast-pkts: '0'
            out-errors: '0'
            out-octets: '0'
            out-unicast-pkts: '0'
          description: null
          enabled: true
          mtu: '1500'
          name: Virtual-Template1
          oper-status: down
          type: Virtual
```

**Review by gdpak — APPROVED** [review]

**Comment by gdpak** [comment]
@wiggimt Good catch. It looks like we should have written 'end' regex also for not rolling up of multiple interfaces into one section. Thanks for the fix.

**Pull request merged**
