### PR TITLE
Fixes #60 - get_facts can't pickle

### LINKED ISSUE #60: get_facts can't pickle...
get_facts soft fails for certain hosts. I've not been able to figure out a pattern yet. 

The playbook run just kinda stops one any affected hosts, without actually failing. Like it's in an infinite loop or something.

```yaml

  - name: use ansible-network provider roles to gather facts
    include_role:
      name: "{{ ansible_network_provider }}"
      tasks_from: get_facts.yaml
    vars:
      subset: 
        - default
    when: ansible_network_os == 'ios'
```

```sh

TASK [ansible-network.cisco_ios : run command and parse output] **********************************************************************************************
Traceback (most recent call last):
  File "/home/4032956/.pyenv/versions/3.6.6/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/4032956/.pyenv/versions/3.6.6/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle StrictUndefined objects
```

### PR DESCRIPTION
**Pull request by LukeDRussell**
Refer to #60 

As an aside, it would be nice if `tests/test_parser_templates.yaml` was included in CI tests.

### CODE REVIEW

**Comment by LukeDRussell** [comment]
recheck

**Comment by LukeDRussell** [comment]
When I run tox locally it shows as a linting error for a file that hasn't changed in 3 months. I suspect this is to do with the strict yaml linting being enabled recently.

```
$ tox
linters create: /Users/4032956/repos/lukerussell.cisco_ios/.tox/linters
linters installdeps: -r/Users/4032956/repos/lukerussell.cisco_ios/test-requirements.txt
linters installed: flake8==3.6.0,mccabe==0.6.1,pathspec==0.5.9,pycodestyle==2.4.0,pyflakes==2.0.0,PyYAML==3.13,yamllint==1.13.0
linters run-test-pre: PYTHONHASHSEED='997758326'
linters runtests: commands[0] | yamllint -s .
linters runtests: commands[1] | flake8
./library/ios_user_manager.py:48:1: W391 blank line at end of file
'''^
ERROR: InvocationError for command '/Users/4032956/repos/lukerussell.cisco_ios/.tox/linters/bin/flake8' (exited with code 1)
______________________________________________________ summary ______________________________________________________
ERROR:   linters: commands failed
```

**Comment by pabelanger** [comment]
I'm not sure what is going on here, let me look into it and push up a fix in another PR.

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Okay, fixed. I've gone a head and cleaned up the failures and enabled more coverage on flake8 rules in our tox.ini file.

**Review by gdpak — APPROVED** [review]
LGTM

**Comment by gdpak** [comment]
gate

**Pull request merged**
