### PR TITLE
add bgp group and prefix-list parser

### PR DESCRIPTION
**Pull request by colin-mccarthy**

### CODE REVIEW

**Comment by privateip** [comment]
@colin-mccarthy why are you suggesting to remove the `extend` directive?

**Comment by colin-mccarthy** [comment]
It is causing my debugs not to work. it's putting everything into one dictionary(cisco_ios).
```  
- debug: var=system
- debug: var=interfaces

```

**Comment by privateip** [comment]
that was by design to avoid namespace clashes.  Im concerned about having such generic names as top level keys.  i offer two alternatives here:

1. make a consistent top level key across all providers (not in favor of this idea)
2. make the top level container configurable with the ability to omit it all together.

thoughts?

**Comment by colin-mccarthy** [comment]
What does your debug look like if you want to see for example just the interface info?

**Comment by privateip** [comment]
`debug: var=cisco_ios.interfaces`

**Comment by colin-mccarthy** [comment]
alright, I'm ok with adding extend back in there for all the parsers. I'll make those changes on my repo.

**Comment by colin-mccarthy** [comment]
Should be good now

**Pull request merged**
